export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const TOGGLE_MINI_CART_HIDDEN = "TOGGLE_MINI_CART_HIDDEN";
export const ICON_CART_HIDDEN = "ICON_CART_HIDDEN";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const SUBTRACT_CART_ITEM = "SUBTRACT_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const UPDATE_COLLECTIONS = "UPDATE_COLLECTIONS";
export const COLLECTIONS_LOADING = "COLLECTIONS_LOADING";
export const COLLECTIONS_LOADED_SUCCESS = "COLLECTIONS_LOADED_SUCCESS";
export const COLLECTIONS_LOADED_FAILED = "COLLECTIONS_LOADED_FAILED";
export const CLEAR_CART = "CLEAR_CART";
// google sign in
export const GOOGLE_SIGNIN_START = "GOOGLE_SIGNIN_START";
export const GOOGLE_SIGNIN_SUCCESS = "GOOGLE_SIGNIN_SUCCESS";
export const GOOGLE_SIGNIN_FAILURE= "GOOGLE_SIGNIN_FAILURE";
// signin/password
export const SIGNINPASSWORD_START = "SIGNINPASSWORD_START";
export const SIGNINPASSWORD_SUCCESS = "SIGNINPASSWORD_SUCCESS";
export const SIGNINPASSWORD_FAILURE = "SIGNINPASSWORD_FAILURE";
// signout
export const SIGNOUT_START = "SIGNOUT_START";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_FAILURE = "SIGNOUT_FAILURE";
// user
export const CHECK_USER_SESSION = "CHECK_USER_SESSION";