export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const TOGGLE_MINI_CART_HIDDEN = "TOGGLE_MINI_CART_HIDDEN";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const SUBTRACT_CART_ITEM = "SUBTRACT_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";